### ISSUE TITLE
[Bug]: Jenkins log no longer contain job success/failure log message

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-ci#290]
### Describe the bug

Till jenkins image version `2.332.3-lts-jdk8` we used to see log messages like `2023-05-19 21:47:45.670+0000 [id=294]	INFO	o.j.p.workflow.job.WorkflowRun#finish: test-demo-job #1 completed: SUCCESS` for each job run, success, failure or aborted. 
Since jenkins logs get pushed tp cloudwatch we used this create alarms over job failures for our internal tracking. 

After the latest update to verion `2.387.1-lts-jdk11` we no longer see such job specific logs in the jenkins.log which is breaking our alerting system. 

### To reproduce

Checkout `jenkins/jenkins:2.387.1-lts-jdk11` image on your local and run jenkins server, add a new test job and run. 
If you check `docker logs` for the container you will not see any job specific job entries.

**Comment by gaiksaya** [comment]
Found a work around this. I tried adding a custom log recorder with below specifications and it worked:

```
  log:
    recorders:
    - loggers:
      - level: "FINE"
        name: "org.jenkinsci.plugins.workflow.job.WorkflowRun"
      name: "workflow-run-logger"
```
Need to add it as configuration as code and enable alarming based on this log file than the default one.
