### ISSUE TITLE
Enable fine grain access per user per workflow or set of workflows

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#507]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/issues/5171
The current jenkins infrastructure has permissions set up which allows only admin or readonly access. See https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/oidc-config.ts#L82-L85

### Describe the solution you'd like

Have more fine grain access such that:
- User A can access:
    - Workflow A
    - Workflow B
    - Workflow C
 - User B can access:
     - Workflow A
     - Everything under folder called `foo`
 
- Default read-only and admin access should be retained as is. 
- Everything including user handle, workflow names or pattern or folder and exact permission should be infrastructure as code.

### Additional context

[Role-based Authorization Strategy](https://plugins.jenkins.io/role-strategy/) plugin and [config](https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/oidc-config.ts#L79) is already being used. Enhance on top of it to give fine grain access.

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/)]

**Comment by gaiksaya** [comment]
Starting with the builder role that would have permissions to build, rebuild, cancel and read jobs. This role would not have access to create or delete or update jobs. 
```yaml
  authorizationStrategy:
    roleBased:
      permissionTemplates:
      - name: "builder-template"
        permissions:
        - "Job/Build"
        - "Job/Cancel"
        - "Job/Discover"
        - "Job/Read"
        - "Lockable Resources/View"
        - "Run/Replay"
        - "Metrics/View"
        - "View/Read"
      roles:
        items:
        - entries:
          - user: "gaiksaya"
          name: "builder-role"
          pattern: "(?i)distribution-.*"
          permissions:
          - "Job/Cancel"
          - "Lockable Resources/View"
          - "Job/Build"
          - "Run/Update"
          - "Job/Discover"
          - "Job/Read"
          - "Metrics/View"
          - "View/Read"
          - "Run/Replay"
          templateName: "builder"
```
